package dam.recuperacion2.Entity;
// Generated 24-may-2021 12:57:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departament generated by hbm2java
 */
public class Departament  implements java.io.Serializable {


     private Integer idDepartament;
     private String nomDepartament;
     private Set professors = new HashSet(0);

    public Departament() {
    }

	
    public Departament(String nomDepartament) {
        this.nomDepartament = nomDepartament;
    }
    public Departament(String nomDepartament, Set professors) {
       this.nomDepartament = nomDepartament;
       this.professors = professors;
    }
   
    public Integer getIdDepartament() {
        return this.idDepartament;
    }
    
    public void setIdDepartament(Integer idDepartament) {
        this.idDepartament = idDepartament;
    }
    public String getNomDepartament() {
        return this.nomDepartament;
    }
    
    public void setNomDepartament(String nomDepartament) {
        this.nomDepartament = nomDepartament;
    }
    public Set getProfessors() {
        return this.professors;
    }
    
    public void setProfessors(Set professors) {
        this.professors = professors;
    }




}


