package dam.recuperacion2.Entity;
// Generated 24-may-2021 12:57:12 by Hibernate Tools 4.3.1



/**
 * Professor generated by hbm2java
 */
public class Professor  implements java.io.Serializable {


     private Integer idProfessor;
     private Departament departament;
     private String nomProfessor;
     private String especialitat;

    public Professor() {
    }

	
    public Professor(Departament departament, String nomProfessor) {
        this.departament = departament;
        this.nomProfessor = nomProfessor;
    }
    public Professor(Departament departament, String nomProfessor, String especialitat) {
       this.departament = departament;
       this.nomProfessor = nomProfessor;
       this.especialitat = especialitat;
    }
   
    public Integer getIdProfessor() {
        return this.idProfessor;
    }
    
    public void setIdProfessor(Integer idProfessor) {
        this.idProfessor = idProfessor;
    }
    public Departament getDepartament() {
        return this.departament;
    }
    
    public void setDepartament(Departament departament) {
        this.departament = departament;
    }
    public String getNomProfessor() {
        return this.nomProfessor;
    }
    
    public void setNomProfessor(String nomProfessor) {
        this.nomProfessor = nomProfessor;
    }
    public String getEspecialitat() {
        return this.especialitat;
    }
    
    public void setEspecialitat(String especialitat) {
        this.especialitat = especialitat;
    }




}


